apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1  # Pod 인스턴스의 수
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx-custom:latest  # 사용할 이미지
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer  # 외부 접근을 위해 LoadBalancer 사용
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx  # Deployment와 일치하는 레이블 선택